### DISCUSSION TITLE
No exit option on the docker image to prevent the container from exiting

### DISCUSSION THREAD

**Discussion by m3h0w** [pkosiec/mongo-seeding#171] [Q&A] [answered]
I'm running the `mongo-seeding` docker image in an e2e test pipeline and since `--exit-code-from <service_x>` option in docker-compose implies `--abort-on-container-exit`, my pipeline gets shutdown when mongo-seeding exits instead when the service_x exits. 

I'd like to make the `mongo-seeding` container sleep or somehow keep running after it has done its job to prevent the `--abort-on-container-exit` being triggered. Is there a way I could do that without the need to modify the image itself? Thanks!

**Comment by m3h0w** [comment]
Here's what I did instead for now:

entry.sh:
```
#!/bin/sh
seed
tail -f /dev/null
```

Dockerfile:
```
FROM pkosiec/mongo-seeding:3.6.0

ENTRYPOINT [ "/app/scripts/entry.sh" ]
```

Plus the relevant service in docker-compose with volumes mount for completeness:
```
  mongo-seed:
    build:
      context: ./mongoSeed
    volumes:
      - ./mongoSeed/data:/app/data
      - ./mongoSeed/scripts:/app/scripts
    working_dir: /app/data
    depends_on:
      - mongodb
```

  [1]: https://github.com/pkosiec/mongo-seeding
  [2]: https://github.com/pkosiec/mongo-seeding/blob/master/docker-image/prod.Dockerfile

**Comment by pkosiec** [comment, marked as answer]
Hi @m3h0w,
You don't need to modify the image. You can easily change the `entrypoint` and `command` via Docker Compose file:
- https://docs.docker.com/compose/compose-file/compose-file-v3/#entrypoint
- https://docs.docker.com/compose/compose-file/compose-file-v3/#command

So, you can try using the same commands you had in the `entry.sh` script:

```yaml
mongo-seed:
  # (...)
  entrypoint: ["sh"]
  command: ["-c", "seed; sleep infinity"]
```

I didn't test it with Docker Compose, but it should work, as the following Docker command works exactly as you would like to:
```bash
docker run --rm --entrypoint="sh" pkosiec/mongo-seeding -c 'seed; sleep infinity'
```

Let me know if that helps. Cheers!
