### ISSUE TITLE
No exit option on the docker image to prevent the container from exiting

### ISSUE THREAD

**Issue by m3h0w** [pkosiec/mongo-seeding#170]
I'm running the `mongo-seeding` docker image in an e2e test pipeline and since `--exit-code-from <service_x>` option in docker-compose implies `--abort-on-container-exit`, my pipeline gets shutdown when mongo-seeding exits instead when the service_x exits. 

I'd like to make the `mongo-seeding` container sleep or somehow keep running after it has done its job to prevent the `--abort-on-container-exit` being triggered. Is there a way I could do that without the need to modify the image itself? Thanks!

**Comment by m3h0w** [comment]
Here's what I did instead for now:

entry.sh:
```
#!/bin/sh
seed
tail -f /dev/null
```

Dockerfile:
```
FROM pkosiec/mongo-seeding:3.6.0

ENTRYPOINT [ "/app/scripts/entry.sh" ]
```

Plus the relevant service in docker-compose with volumes mount for completeness:
```
  mongo-seed:
    build:
      context: ./mongoSeed
    volumes:
      - ./mongoSeed/data:/app/data
      - ./mongoSeed/scripts:/app/scripts
    working_dir: /app/data
    depends_on:
      - mongodb
```

  [1]: https://github.com/pkosiec/mongo-seeding
  [2]: https://github.com/pkosiec/mongo-seeding/blob/master/docker-image/prod.Dockerfile
