### ISSUE TITLE
Add a way to add data into multiple databases (specifically admin & app db)

### ISSUE THREAD

**Issue by hongkongkiwi** [pkosiec/mongo-seeding#73]
Let me explain the use for this case.

Right now, I have a docker spinning up a mongodb database. Assuming that the database is totally empty I want to seed using "pkosiec/mongo-seeding" docker.  

There's just one catch, I want to also seed mongodb users. These reside in the "admin" database, while my data is in an "app" database.

I worked around it by using a shell script to seed the db users when the mongodb docker spins up, then running the seeding docker.

It's really not ideal though, I'd like to use this docker to seed both db users in the admin database as well as my application data.

Any ideas on this one?

**Comment by pkosiec** [comment]
Hello @hongkongkiwi! 

Theoretically I could change the input data directory structure for Mongo Seeding and put another directory level on top of the existing one. The directory name would point to the database name. But, similarly to your case, most users want to provide different credentials to access different databases. That would make the whole `mongo-seeding` configuration quite complicated.

As you are using `mongo-seeding` Docker image, I would suggest running another instance in second container, side by side with the first one. The first one would seed users, and the second one - app data. 
I think that would be the best solution to what you want to achieve. If you use `docker-compose`, or even if not, that won't be too complicated.

Tell me what do you think about this suggestion 🙂If it's not satisfying, we'll try to figure it out. I'm open for any ideas.

**Comment by hongkongkiwi** [comment]
Hi @pkosiec , thanks for the reply.

I actually highly recommend an option to have an additional parent directory. It could be only used if we have an extra ENV var (that way we dont break backwards compatibility), for example `SUPPORT_MULTIPLE_DATABASES=true`. This is always set to false if the db name is already set via an ENV vari.

Then the structure could be /db/collection/*.js

On the other hand, I have another idea to solve this. How about if we allow two different formats for the JSON being inserted. 
Method 1 (legacy):
```javascript
module.exports = {
    bar: "foo"
}
```
Method 2 (new method)
```javascript
module.exports = {
    options: {
        db: 'mydbname'
       collection: 'mycollectionname'
       db_username: 'myusername',
       db_password: 'mypassword'
    },
    data: {
      bar: "foo"
   }
}
```

In this way, if no special options are specified and it just works at present, however if options are specified it will use those to connect. All of the options can be optional and override existing values.

What do you think?

The problem with using the method you mentioned with docker-compose is that `depends_on` does not actually wait for the service to finish or become ready. It simply waits for the container to start. That means if we have lots of data in multiple databases then it's going to try to insert them almost all at once if the container starts quickly and going to cause a kind of race condition. If the app data gets there first, the users won't be ready.

**Comment by pkosiec** [comment]
The first idea is my favorite one - so I would pick extending data import directory structure and toggling multiple database support with env variable. I will try to implement the feature in the coming weeks.

In the meantime I would use `depends_on` with a trick - consider the following docker-compose config:

```yaml
version: '3'
services:
  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=EXAMPLE_ACCESS_KEY
      - MINIO_SECRET_KEY=EXAMPLE_SECRET_KEY
    command: server /tmp/minio
  app_being_tested:
    build:
      context: ../
      dockerfile: ./Dockerfile
    depends_on:
    - minio
    command: sh -c 'while ! nc -z minio 9000; do sleep 1; done; /app/main'
    links:
    - minio
    volumes:
      - ./testdata/:/app/data/
    environment: &appConfig
      - APP_UPLOAD_ENDPOINT=minio
      - APP_UPLOAD_ACCESS_KEY=EXAMPLE_ACCESS_KEY
      - APP_UPLOAD_SECRET_KEY=EXAMPLE_SECRET_KEY
      - APP_UPLOAD_PORT=9000
      - APP_UPLOAD_SECURE=false
```

Here I start `minio` container and, once the Minio app is ready, the tested app launches.

So, in your case, I would modify the `command` to try to connect to MongoDB database as an user which should be inserted with first `mongo-seeding` container, which populates the users.

Anyway, thanks again for submitting the idea for the new feature. It is planned for 3.3.0 release.
Cheers!
